#!/usr/bin/env bash

if [[ $# -lt 1 ]]; then
  tree -L 1
elif [[ $# -eq 1 ]] && [[ $1 =~ ^a$ ]]; then
  tree -aL 1
elif [[ $# -eq 1 ]] && [[ $1 =~ ^[0-9]$ ]]; then 
  tree -L $1
elif [[ $# -eq 1 ]] && [[ $1 =~ ^a[0-9]$|^[0-9]a$ ]]; then
  tree -aL ${1//a/}
else 
  echo "lt: invalid argument"
fi